### ISSUE TITLE
release fails to build with ubuntu-22.04, ubuntu-24.04

### ISSUE THREAD

**Issue by keiravillekode** [joshgoebel/wren-console#26]
Build failure occurred when attempting to update Exercism wren's `.github/workflows/ci.yml` from ubuntu-20.04 (which is no longer supported by Github Actions)

https://github.com/exercism/wren/actions/runs/14477995277/job/40608178725?pr=234
runs-on: ubuntu-24.04

https://github.com/exercism/wren/actions/runs/14478750113/job/40610712294?pr=234
runs-on: ubuntu-22.04

```
Run cd wren-console
make: Entering directory '/home/runner/work/wren/wren/wren-console/projects/make'
==== Building wrenc (release_64bit) ====
Creating obj/64bit/Release
Creating ../../bin

...


resolver.c
scheduler.c
signal.c
stream.c
../../src/cli/resolver.c:94:13: error: conflicting types for ‘write’; have ‘void(WrenVM *, const char *)’
   94 | static void write(WrenVM* vm, const char* text)
      |             ^~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /usr/include/x86_64-linux-gnu/sys/param.h:28,
                 from ../../deps/libuv/include/uv/unix.h:41,
                 from ../../deps/libuv/include/uv.h:66,
                 from ../../src/cli/resolver.c:2:
/usr/include/unistd.h:378:16: note: previous declaration of ‘write’ with type ‘ssize_t(int,  const void *, size_t)’ {aka ‘long int(int,  const void *, long unsigned int)’}
  378 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
make[1]: *** [wrenc.make:461: obj/64bit/Release/resolver.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:42: wrenc] Error 2
make: Leaving directory '/home/runner/work/wren/wren/wren-console/projects/make'
Error: Process completed with exit code 2.
```

Exercism is using wren-console v0.3.1

**Comment by joshgoebel** [comment]
For anyone with time to pick this up before I get to it I think there is a patch against wren-cli that fixes the `write` issue with newer libcs... that could probably be easily pulled over into wren-console.

**Comment by keiravillekode** [comment]
This might have already been fixed in https://github.com/joshgoebel/wren-console/commit/742cd837677b81155b59862fdd497cdf2ac28814

Perhaps this only needs a new release.  Exercism wren's `.github/workflows/ci.yml` and  `docs/INSTALLATION.md` would then be updated to use the new release instead of 0.3.1

**Comment by keiravillekode** [comment]
Using master works with ubuntu-24.04. So a new release would be excellent. For now we are using master.

A new release of the github action `joshgoebel/install_wren_console` is perhaps more needed.

When I [attempt](https://github.com/exercism/wren-test-runner/pull/36)

```
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: install wren-console
        uses: joshgoebel/install_wren_console@57ab2c4063656330e748b2cbd4beaeac30112a80
```

it [fails](https://github.com/exercism/wren-test-runner/actions/runs/15959488313/job/45010064338?pr=36) in the same way:


```
../../src/cli/resolver.c:94:13: error: conflicting types for ‘write’; have ‘void(WrenVM *, const char *)’
   94 | static void write(WrenVM* vm, const char* text)
      |             ^~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /usr/include/x86_64-linux-gnu/sys/param.h:28,
                 from ../../deps/libuv/include/uv/unix.h:41,
                 from ../../deps/libuv/include/uv.h:66,
                 from ../../src/cli/resolver.c:2:
/usr/include/unistd.h:378:16: note: previous declaration of ‘write’ with type ‘ssize_t(int,  const void *, size_t)’ {aka ‘long int(int,  const void *, long unsigned int)’}
  378 | extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur
      |                ^~~~~
make[1]: *** [wrenc.make:461: obj/64bit/Release/resolver.o] Error 1
```

**Comment by joshgoebel** [comment]
https://github.com/joshgoebel/wren-console/pull/27
